
<!--<div class="mobile-menu pushy pushy-left">
    <ul>
        <li><a href="#">MEN</a></li>
        <li><a href="#">Whomen</a></li>
        <li><a href="#">Item 3</a></li>
        <li><a href="#">Item 4</a></li>
        <li><a href="#">Item 5</a></li>
        <li><a href="#">Item 6</a></li>
    </ul>
</div>-->
<div class="mobile_menu_logo">
    <a class="logo" href="<?php echo $this->getUrl('') ?>">
        <img src="<?php echo $this->getSkinUrl() ?>images/logo-mobile.gif" alt="<?php echo $this->getLogoAlt() ?>" class="small" />

    </a>
</div>
<div class="mobile_menu_minicart">
    <?php echo $this->getChildHtml('minicart_head_mobile') ?>
</div>
<div class="mobile_menu_login">
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo $this->__('Login') ?></a>
    <?php else: ?>
        <a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>"><?php echo $this->__('Logout') ?></a>
    <?php endif; ?>
</div>
<div class="mobile_menu_category">
    <?php echo $this->getChildHtml('topMenu') ?>
</div>

