<div class="no-margin slidemenu">
    <input id="toggle-right" class="slidemenu-check" type="checkbox"><label id="slidemenu-label" for="toggle-right"></label>
    <div class="header_bot_links slidemenu">
        <ul class="nav-justified header_bot_links_ul">
            <li><a>WOMEN</a></li>
            <li><a>MEN</a></li>
            <li><a>SALE</a></li>
            <li><a>BRANDS</a></li>
        </ul>
    </div>
    <div id="content" class="content2">
        fdsgfdgdfglksdfglksjglksalksadjfglds;kjgsl;kgjsfdl;kjgs;<lkgjsl></lkgjsl>
    </div>
</div>

